# Generated by Django 5.1 on 2024-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_collectionmovies_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genres",
            options={
                "ordering": ["-movie_count"],
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.AlterField(
            model_name="genres",
            name="movie_count",
            field=models.BigIntegerField(default=1, verbose_name="Movie Count"),
        ),
    ]
