# Generated by Django 5.1 on 2024-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_favourite",
            field=models.BooleanField(default=False, verbose_name="Is Favourite"),
        ),
    ]
