# Generated by Django 5.1 on 2024-08-09 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_collection_is_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
